### ISSUE TITLE
Api for list of policies

### ISSUE THREAD

**Issue by Korakbhakta02** [eclipse-ditto/ditto#1955] opened 2024-06-07 10:09 UTC
Hi, 
 I want to list the policies according to the user by which the policies are created. Let users be A,B and C. So, user A will get the policies made by A only,not B and C. Is there any api for this service or any method to get such list? Thanks in advance.

**Comment by thjaeckle** [comment] 2024-06-07 12:00
Unfortunately, this functionality does not exist yet.
Issue: #1683

**Comment by Korakbhakta02** [comment] 2024-06-07 13:15
Is there any chance for the availability of this service in coming future?

**Comment by thjaeckle** [comment] 2024-06-07 13:47
It is an OpenSource project - so if anybody picks it up and provides a PR for it, sure ..

There already was an attempt by the Ditto community in PR #1698 - but that PR was in a very early stage when work on it was again stopped.

Personally, I don't have plans to work on this in the near future.

**Comment by thjaeckle** [comment] 2024-06-11 07:24
Closing as duplicate of https://github.com/eclipse-ditto/ditto/issues/1683

**Closed by thjaeckle** 2024-06-11 07:24 UTC
