### ISSUE TITLE
Modify connection does not work with Ditto 3.2.1

### ISSUE THREAD

**Issue by mladBlum** [eclipse-ditto/ditto#1625] opened 2023-04-26 10:03 UTC
Today we upgraded our Ditto from version 3.1.2 to version 3.2.1.
In Ditto 3.2.1 we are not able to modify a connection. 

Our Setup:
- AKS (Kubernetes Cluster)
- Ditto installed via Helm-Chart (Chart Version 3.2.2)

Steps to reproduce:

1. Create the connection
```
curl --request POST \
  --url 'https://example.com/devops/piggyback/connectivity?timeout=10' \
  --header 'authorization: Basic xxxxx' \
  --header 'content-type: application/json' \
  --data '{"targetActorSelection": "/system/sharding/connection","headers": {"aggregate": false},"piggybackCommand": {"type": "connectivity.commands:createConnection","connection": {"id": "mqtt-broker-airqube","connectionType": "mqtt","connectionStatus": "open","failoverEnabled": true,"uri": "tcp://eclipse-mosquitto-internal.mosquitto:1883","sources": [{"addresses": ["device/airqube/#"],"authorizationContext": ["mosquitto:device"],"qos": 0,"filters": []}],"targets": [{"address": "device/{{ thing:id }-in}","topics": ["_/_/things/twin/events","_/_/things/live/messages"],"authorizationContext": ["nginx:ditto"],"qos": 0}]}}}'
```
2. Add name "mqtt helloworld" by modifying the connection
```
  curl --request POST \
  --url 'https://example.com/devops/piggyback/connectivity?timeout=20' \
  --header 'authorization: Basic xxxxx' \
  --header 'content-type: application/json' \
  --data '{"targetActorSelection": "/system/sharding/connection","headers": {"aggregate": false},"piggybackCommand": {"type": "connectivity.commands:modifyConnection","connection": {"id": "mqtt-broker-airqube","name": "mqtt helloworld","connectionType": "mqtt","connectionStatus": "open","failoverEnabled": true,"uri": "tcp://eclipse-mosquitto-internal.mosquitto:1883","sources": [{"addresses": ["device/airqube/#"],"authorizationContext": ["mosquitto:device"],"qos": 0,"filters": []}],"targets": [{"address": "device/{{ thing:id }-in}","topics": ["_/_/things/twin/events","_/_/things/live/messages"],"authorizationContext": ["nginx:ditto"],"qos": 0}]}}}'
```

3. The endpoint answers with the following message
```
HTTP/1.1 200 OK
Date: Wed, 26 Apr 2023 10:00:13 GMT
Content-Type: application/json
Content-Length: 159
Connection: close
correlation-id: 1dff9b1d-81f2-4ce7-97b2-8f5fbee5b8d4
timeout: 20
response-required: false
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Strict-Transport-Security: max-age=15724800; includeSubDomains

{
  "status": 503,
  "error": "ask.error",
  "message": "There was an internal timeout.",
  "description": "Please retry the performed action in order to improve resiliency."
}
```

**Comment by thjaeckle** [comment] 2023-04-26 10:33
The "old API" for accessing connection still should work.
However, just to check: did you try the newly introduced `/connections` API to modify your connection?
https://www.eclipse.org/ditto/http-api-doc.html#/Connections/put_connections__connectionId_

Credentials are the same as for the `/devops` resources..

**Comment by mladBlum** [comment] 2023-04-26 12:07
I have just done the same calls with the /connections API. This works just fine, the new endpoint does not crash. 
Thanks for the hint, for some reason we didn't noticed that there is a new endpoint.

Should we leave the issue open? After all, the piggyback API is not yet marked as obsolete in the documentation.

**Comment by thjaeckle** [comment] 2023-04-26 12:24
You can leave it open - maybe someone will look into it..

**Comment by thjaeckle** [comment] 2023-11-23 07:09
I think noone is going to look into this.
Closing as I also could not reproduce lately.

**Closed by thjaeckle** 2023-11-23 07:09 UTC
