### ISSUE TITLE
Unable to deploy with Kubernetes Minikube

### ISSUE THREAD

**Issue by Suyasharya165** [eclipse-ditto/ditto#1539] opened 2022-11-30 09:54 UTC
Hi Team,

As per the recommendations given in the link 
https://github.com/eclipse-ditto/ditto/blob/master/deployment/kubernetes/README.md

I have tried to install ditto using Kubernetes today , How ever I don't see all the pods are running .

adding below screenshot for your reference

![Screenshot from 2022-11-30 15-17-54](https://user-images.githubusercontent.com/76938754/204763774-e72cf075-3258-4d97-9bc9-7c83c9a886c1.png)

When I go and check the logs - I see below error 
Error: Unable to access jarfile starter.jar

Can you please help me with it.

**Comment by thjaeckle** [comment] 2022-11-30 13:11
This unfortunately is a known issue: #1523

Maybe I can find some time working on a fix.

**Comment by thjaeckle** [comment] 2022-12-02 09:41
@Suyasharya165 the issue is fixed in the descriptor file on "master" branch

**Closed** 2022-12-02 09:40 UTC
